# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8f609f867e2a0d7cb4d943d533eaa9f476f9a5b478c91a0edb7dc68b16009d7455df7c845e6a3301d3cab6c99c4ea92fa23b80f0bb342b45f8d104c06b2df10

test:
  secret_key_base: 1ecd905d201bc53e2259ca1ae9e1c91827efdac26ce67350dc6d7aa6a59a36481a1b7d60a09509e603d8966bf895bc24fe041b4d8f785fbbfd61ad07d7cf752d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
